server:
  port: 8080

spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.1.138
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        hostname: 127.0.0.1