server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.138:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'