server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  # consul 注册中心地址
  cloud:
    consul:
      host: 192.168.1.138
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        hostname: 127.0.0.1