server:
  port: 8001

spring:
  application:
    name: cloud-payment-service #服务名称
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
      # 采样率值介于 0-1 之间，1 表示全部采集链路信息
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: root

eureka:
  client:
    # 是否将自己注册进 eureka-server 默认为true
    register-with-eureka: true
    # 是否从 eureka-server 抓取已有的注册信息，默认为true
    # (单点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡)
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址
      #       defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 访问路径可以显示IP地址
    # Eureka 客户端向服务端发送心跳的时间间隔(秒)
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务端收到最后一次心跳等待的时间上限(默认90秒),超时清除客户端
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kiger.springcloud.entity  #所有entity别名所在包