server:
  port: 8080

spring:
  application:
    name: consumer-feign-order

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/

# 设置feign客户端超时时间（OpenFeign默认支持Ribbon）
ribbon:
  # 建立连接所需的时间，适用于网络状况正常情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 建立连接后从服务端读取到可用资源所用的时间
  ConnectTimeout: 5000

# feign日志监控
logging:
  level:
    # feign日志以哪个级别来监控哪个接口
    com.kiger.springcloud.service.PaymentFeignService: debug
